version: 0.0
os: linux
files:
    - source: /
      destination: /home/ec2-user/my-app
permissions:
    - object: /home/ec2-user/my-app/
      pattern: '**'
      owner: ec2-user
      group: ec2-user
# hooks:
#     AfterInstall:
#         - location: CICDTestAPI/scripts/start-application.sh
#           timeout: 300
#           runas: ec2-user
