version: 0.0
os: linux
files:
    - source: /
      destination: /home/ec2-user/my-app
      overwrite: yes
permissions:
    - object: /
      pattern: '**'
      owner: ubuntu
      group: ubuntu
hooks:
    AfterInstall:
        - location: CICDTestAPI/scripts/start-application.sh
          timeout: 300
          runas: ubuntu
