version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/cicdtest
      overwrite: yes
permissions:
    - object: /
      pattern: '**'
      owner: ubuntu
      group: ubuntu
hooks:
    AfterInstall:
        - location: start-application.sh
          timeout: 300
          runas: ubuntu
